### ISSUE TITLE
i18n - translation in search result bug and wrong redirect after page delete

### ISSUE THREAD

**Issue by eukraina** [Cotonti/Cotonti#1571]
i18n И коробочный плуг серч, ищет в переводах но не на языке оригинала. Если на стр поиска указать рубрику где искать явно (например запись есть в News и указать в списке выпадающем Ньюз) то наоборот ищет по языку оригинала но не ищет по переводам. 
Трабла начинается тут
https://github.com/Cotonti/Cotonti/blob/master/plugins/i18n/i18n.search.query.php#L19 Судя по всему.

**Comment by eukraina** [comment]
https://github.com/Cotonti/Cotonti/blob/master/plugins/i18n/inc/i18n.page.php#L208
Неверный редирект после удаления
У себя исправил так
$page_urlp = empty($pag['page_alias']) ? 'c=' . $pag['page_cat'] . "id=$id" : 'c=' . $pag['page_cat'] . '/' . $pag['page_alias'];

**Comment by CrazyFreeMan** [comment]
В котонті немає i18n. Забудьте і не користуйтесь, максимум це переклади string файлів. Те що є дика пародія, нічого путнього не вийде зробити (хто б там що не казав, перевірив на собі)

**Comment by seditio** [comment]
Плохо перевирив

**Comment by CrazyFreeMan** [comment]
Поиск не работает. Сделайте перевод всего контента в модуле и чтоб был поиск. Контент в модулях из коробки также не переводится (голосовалка та же).
Очень усложнено все и багов куча. потому я констатирую что отсутстувует мультиязычность. Сделать нормальный многоязычный сайт (магазин, портал) - поще не на котонти.

**Comment by macik** [comment]
@eukraina на счет строки #L208 — да, полагаю там ошибка. Но исправили вы ее не корректно (ваш вариант не сработает в случае альяса и отключенных SEF URLs, а так же не будет работать в случае отсутствия альяса).

Должно быть примерно так:
```php
$page_urlp = empty($pag['page_alias']) ? 'c=' . $pag['page_cat'] . "&id=$id" : 'c=' . $pag['page_cat'] . '&al=' . $pag['page_alias'];
```
прошу проверить...

**Comment by Dayver** [comment]
Put together info for `i18n` plugin bugs and misc...

- [ ] adding secondary locale first #1272

- [ ] comments support #1273

- [ ] Page Taglist inconsistent when i18n used #1460

- [ ] i18n not consider source page parsing mode #1504

- [ ] SEO fix work incorrect for main page #1615

**Comment by Alex300** [comment]
Tasks from [Dayver](https://github.com/Dayver) are moved in commot i18n topic: https://github.com/Cotonti/Cotonti/issues/1664

**Comment by Alex300** [comment]
Translation in search result bug is fixed. Please test it.
