### ISSUE TITLE
'i18n' plugin improvements, fixes and misc...

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1664]
Put together info for `i18n` plugin bugs and misc...

- [ ] adding secondary locale first #1272

- [ ] comments support #1273

- [ ] Page Taglist inconsistent when i18n used #1460

- [ ] i18n not consider source page parsing mode #1504

- [ ] SEO fix work incorrect for main page #1615

- [x] i18n not working with page enum #1645

_Originally posted by @Dayver in https://github.com/Cotonti/Cotonti/issues/1571#issuecomment-527249941_
