### ISSUE TITLE
Tags refactor and improvements

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1761]
[RU]

- [ ] Если тега нет - отдавать 404. (https://github.com/Cotonti/Cotonti/issues/1755)
- [ ] Если тег есть и нет привязанных элементов то 200 и сообщение "ничего не найдено". (https://github.com/Cotonti/Cotonti/issues/1755)
- [ ] Удаление тега в админке с подтверждением "К тегу привязано N элементов. Подтвердите действие" (https://github.com/Cotonti/Cotonti/issues/1755)
- [ ] Использовать `cot_generatePaginationTags()` для вывода тегов пагинации (https://github.com/Cotonti/Cotonti/issues/1755)
- [ ] Добавить canonical url для тегов (https://github.com/Cotonti/Cotonti/issues/1755)
