### ISSUE TITLE
Front End modernisation

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1790]
[RU]
Модернизация фронта:

- [x] Для удобства разработки разделить код файлы **js/base.js** на отдельные файлы (компоненты) https://github.com/Cotonti/Cotonti/issues/1794
- [x] JavaScript Транспорт для периодических запросов. https://github.com/Cotonti/Cotonti/issues/1795
- [x] Добавить в коробку [Bootstrap](https://getbootstrap.com/docs/5.3/getting-started/introduction/) https://github.com/Cotonti/Cotonti/issues/1824
- [ ] Добавить в коробку [Select2](https://select2.org/). Это select с поиском по подстроке, ajax-подгрузкой для огромных списков опций и удобным мультиселектом. Теги и мультиселекты переписать на использование его. https://github.com/Cotonti/Cotonti/issues/1873
- [ ] Automplete обновить для нормальной работы с поледней версией jQuery. В идеале не использовать jQuery
- [ ] DatePicker, DateTimePicker. Желательно без использования jQuery. Наши пикеры на куче селектов переписать на него (`cot_selectbox_date()`).
- [x] API для вывода модальных окон и pop-up-ов на подобие jQuery.toast()
- [ ] Ссылки вида `<a class="modal" href="...">` загружают контент по урлу из атрибута 'href' и отображают его в модальном окне. Сейчас у нас так работают только подтверждение действий. Надо расширить это для любого контента. Удобно, например для всплывающих форм.
- [ ] Подтверждение действий без ajax. Открывать модальный диалог без запроса на сервер.
- [ ] Убрать настройки **Включить ajax** и **Подтверждать опасные действия**. Расширения должны решать сами без глобальных настроек.
- [ ] https://github.com/Cotonti/Cotonti/issues/1728
- [ ] Новая современная адаптивная дефолтная тема (Вроде была задача, надо еще раз поискать)
- [ ] Новая современная адаптивная темя для админки https://github.com/Cotonti/Cotonti/issues/1078
- [ ] По возможности переписать base.js без jQuery.
- [ ] Убрать jQuery из коробки (или обновить до последней версии)
- [ ] Resources класс возможность подключать файлы в header независимо от того выполнился он или нет.
- [ ] Resources класс - консолидация рессурсов и для футера
- [ ] https://github.com/Cotonti/Cotonti/issues/1396
- [ ] https://github.com/Cotonti/Cotonti/issues/1594
- [x] https://github.com/Cotonti/Cotonti/issues/1655

Linked issues:
https://github.com/Cotonti/Cotonti/issues/1760

**Comment by Kabak** [comment]
Изменить дефолтную тему на новую ЛЁГКУЮ без  Бутстрэп , но с  использованием новых плагинов от Kort  ( catlist, comlist , forman , pagelist )
Вы уверены, что нужно превратить элегантный и лёгкий по весу ( 3.6 мб ) Cotonti  в жирного кота , только потому , что кому-то хочется из-за пары тем увеличить размеры движка **в 27 раз** ? 

1) Поместив Бутстрэп в коробку вы убъете самую важную и отличительную фишку Cotonti от всех побобных CMS.
2) придётся каждый раз обновлять Cotonti только потому что обновился Бутстрэп.  Вы теряете автономность и независимость.  Так же как и с CKEditor  приходится каждый раз переписывать движок под новую версию

**Comment by seditio** [comment]
Полный Бутстрап в зипе весит полтора мегабайта. 27 раз ну никак не получается) И нужен он не из-за пары тем -- это точно.
Минорные обновления BS ничего принципиального за собой не тянут, так что обновления проблемой не станут. CKEditor же не становится)
Сайт хорош когда делается быстро и технически корректно. Про узнаваемость BS даже не будем начинать. Загрузку тоже можно кастомизировать -- reboot, grid, utilities. А в разработке своего CSS-фреймворка лично я уже давно смысла не вижу. И таких большинство. Ориентируемся мы все же на разработчиков, а не на владельцев одного-двух персональных сайтов, которые пилятся годами на локалхосте. Таков путь)
Я бы обсудил обвес селектов и date-пикеры. Хотя и здесь тоже надо переходить на современные и (что важнее) надежные и проработанные решения.
Bootstrap в любом случае для админки идеальный вариант. Но и его глобальная отключабельность - вообще не вопрос.

**Comment by Kabak** [comment]
"Bootstrap в любом случае для админки идеальный вариант. Но и его глобальная отключабельность - вообще не вопрос."

Зачем он в коробке, если его можно будет отключить ?
Лучше чтобы для конкретной темы было указано, что нужно установить Бутстреп.  Развёрнутый Бутстреп весит > 100 Mb    и будет только расти.

Дефолтная тема должна быть суперлёгкой и красивой.  Не важно на бутстрепе она бюудет или нет,  нужно оставить для неё из Бутстрепа только то, что тема реально использует и выкинуть всё что просто свинцовым грузом прикрепляется , но не используется.

Есть ли какая-нибудь утилита, которая выкидыывает из огромного Бутстрепа то, что не используется для реальной темы ?  Нужно облегчать Бутстреп и не тянуть в коробку Cotonti вевсь Бутстреп

**Comment by seditio** [comment]
> Зачем он в коробке, если его можно будет отключить ? Лучше чтобы для конкретной темы было указано, что нужно установить Бутстреп. Развёрнутый Бутстреп весит > 100 Mb и будет только расти.

В развернутом виде Бутстрап занимает 8,5 Мб. Если использовать min-версии, 3,6 Мб. Откуда 27 раз и 100 Мб??

> Дефолтная тема должна быть суперлёгкой и красивой. Не важно на бутстрепе она будет или нет, нужно оставить для неё из Бутстрепа только то, что тема реально использует и выкинуть всё что просто свинцовым грузом прикрепляется , но не используется.

Совершенно верно: Бутстрап никак не влияет на элегантность, но удобен (и был разработан) специально для админок. Это готовые элементы для встраивания в нее и с возможностью их кастомизации. 

> Есть ли какая-нибудь утилита, которая выкидыывает из огромного Бутстрепа то, что не используется для реальной темы ? Нужно облегчать Бутстреп и не тянуть в коробку Cotonti вевсь Бутстреп

В 100500 раз повторяю: или просто не грузи утилиты или перекомпилируй дистрибутив под себя. Сколько можно об одном и том же?
